source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JHAnimation_Example' do
  pod 'JHAnimation', :path => '../'

  target 'JHAnimation_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase', :git => 'https://github.com/facebook/ios-snapshot-test-case.git', :commit => 'b898c25'
  pod 'Nimble-Snapshots'
  end
end
